<a href="https://colab.research.google.com/github/kemaladamr/pandas/blob/main/Numpy_and_Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
array_list = [[100, 64, 160],
              [150, 82, 200],
              [90, 55, 80],
              [130, 73, 220],
              [190, 80, 150]]

In [2]:
array_list[1][2]

200

In [3]:
array_list[3][0]

130

In [4]:
array_list

[[100, 64, 160], [150, 82, 200], [90, 55, 80], [130, 73, 220], [190, 80, 150]]

In [5]:
import array as arr
arr_x = arr.array("d", [98.6, 22.35, 72.1])

In [6]:
arr_x

array('d', [98.6, 22.35, 72.1])

In [7]:
ndarray = ([[100, 65, 160],
               [150, 82, 200],
               [90, 55, 80],
               [130, 73, 220],
               [190, 80, 150]],
              [[95, 68, 140],
               [145, 80, 222],
               [90, 62, 100],
               [150, 92, 200],
               [140, 60, 90]],
              [[110, 72, 160],
               [160, 95, 185],
               [100, 80, 110],
               [140, 92, 120],
               [100, 55, 100]])

In [8]:
ndarray

([[100, 65, 160],
  [150, 82, 200],
  [90, 55, 80],
  [130, 73, 220],
  [190, 80, 150]],
 [[95, 68, 140], [145, 80, 222], [90, 62, 100], [150, 92, 200], [140, 60, 90]],
 [[110, 72, 160],
  [160, 95, 185],
  [100, 80, 110],
  [140, 92, 120],
  [100, 55, 100]])

In [9]:
import numpy as np

In [10]:
array1d = np.array([1, 2, 3, 4])
array1d

array([1, 2, 3, 4])

In [11]:
array2d = np.array([[0, 1, 2], [2, 3, 4]])
array2d

array([[0, 1, 2],
       [2, 3, 4]])

In [12]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
np.zeros((2, 1, 3))

array([[[0., 0., 0.]],

       [[0., 0., 0.]]])

In [14]:
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(N=2, M=3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [16]:
np.eye(N=4, M=3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [18]:
np.arange(2, 13, 3)

array([ 2,  5,  8, 11])

In [19]:
np.linspace(start=5, stop=10, num=20)

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [20]:
np.random.rand(2,4)

array([[0.69483606, 0.5657915 , 0.16637896, 0.50095099],
       [0.60512671, 0.85639719, 0.06952844, 0.71946778]])

In [21]:
np.random.randn(2,4)

array([[ 0.48279662,  0.73914042, -0.60830605,  0.733453  ],
       [-1.05096405,  1.06703027, -0.77897305,  1.66746559]])

In [22]:
5 * np.random.randn(2, 4) + 10

array([[11.46968136, 10.70248254, 13.25239064, 11.23452249],
       [11.14069276, 15.59925147,  4.77936351,  4.98901601]])

In [23]:
np.random.randint(2, 5, (2, 3))

array([[3, 2, 2],
       [3, 2, 2]])

In [24]:
np.empty([4,3])

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# The 2D input matrix for diag function
arr_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# Getting diagonal of the array
np.diag(arr_a)

array([1, 5, 9])

In [27]:
# Construct diagonal matrix from a 1D array
# diag returns a 1D array of diagonals for a 2D input matrix.
# This 1D array of digonal can be used here
np.diag(np.diag(arr_a))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [30]:
# Creating diagonal matrix with diagonals other than main diagonal
np.diag(np.diag(arr_a, k=-1))

array([[4, 0],
       [0, 8]])

In [31]:
# Repeating a 1D array 2 times
np.tile(np.array([1, 2, 3]), 2)

array([1, 2, 3, 1, 2, 3])

In [32]:
# Repeating 2D array 4 times
np.tile(np.array([[1, 2, 3], [4, 5, 6]]), 4)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [34]:
# Repeating a 2D array 4 times along axis 0 and 1 time along axis 1
np.tile(np.array([[1, 2, 3], [4, 5, 6]]), (4, 1))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [35]:
np.array([-2, -1, 0, 1, 2], dtype="float")

array([-2., -1.,  0.,  1.,  2.])

In [37]:
np.array([-2, -1, 0, 1, 2], dtype="str")

array(['-2', '-1', '0', '1', '2'], dtype='<U2')

In [43]:
np.array([-2, -1, 0, 1, 2], dtype=str)

array(['-2', '-1', '0', '1', '2'], dtype='<U2')

In [38]:
np.array(["a", "bb", "ccc", "dddd", "eeeee"])

array(['a', 'bb', 'ccc', 'dddd', 'eeeee'], dtype='<U5')

In [39]:
# Boolean array
np.array([True, False, True, True]).dtype

dtype('bool')

In [40]:
np.array([0, 1, 1, 0, 0], dtype="bool")

array([False,  True,  True, False, False])

In [42]:
np.array([0, 1, 0, 0], dtype=bool)

array([False,  True, False, False])

In [44]:
np.array([0, 1, 2, 3, -4], dtype=bool)

array([False,  True,  True,  True,  True])

In [46]:
# Complex array
np.array([[1+ 1j, 2 + 2j], [3 + 3j, 4 + 4j]]).dtype

dtype('complex128')